# SPDX-License-Identifier: Apache-2.0

# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    allow:
      - dependency-name: "@tazama-lf/frms-coe-lib"
      - dependency-name: "@tazama-lf/frms-coe-startup-lib"
    registries:
      - github

registries:
  github:
    type: "npm-registry"
    url: "https://npm.pkg.github.com"
    token: "${{ secrets.GH_TOKEN }}"
